name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

  repository_dispatch:
    types: [Dispatched from PrivateFileShare]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout AltFileShare
        uses: actions/checkout@v3
        with:
          repository: Kee7702/AltFileShare
          token: ${{ secrets.TOKEN }}
          path: ./${{ secrets.AFS_ID }}
      - name: Checkout ToolboxStaffShare
        uses: actions/checkout@v3
        with:
          repository: Kee7702/ToolboxStaffShare
          token: ${{ secrets.TOKEN }}
          path: ./${{ secrets.TSS_ID }}
      - name: Move BilligerHost Contents
        run: mv -f ${{ secrets.TSS_ID }}/billigerhost billigerhost
      - name: Download TSS LargeStorage
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "largestorage"
          out-file-path: ./${{ secrets.TSS_ID }}
      - name: Download 00010101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00010101 }}.md
          out-file-path: ./resolve
      - name: Download 00010102 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00010102 }}.md
          out-file-path: ./resolve
      - name: Download 00010201 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00010201 }}.md
          out-file-path: ./resolve
      - name: Download 00020101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00020101 }}.md
          out-file-path: ./resolve
      - name: Download 00030101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00030101 }}.md
          out-file-path: ./resolve
      - name: Download 00040101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00040101 }}.md
          out-file-path: ./resolve
      - name: Download 00050101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00050101 }}.md
          out-file-path: ./resolve
      - name: Download 00060101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00060101 }}.md
          out-file-path: ./resolve
      - name: Download 00060102 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00060102 }}.md
          out-file-path: ./resolve
      - name: Download 00070101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00070101 }}.md
          out-file-path: ./resolve
      - name: Download 00070102 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00070102 }}.md
          out-file-path: ./resolve
      - name: Download 00080101 resolve 
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "Kee7702/ToolboxStaffShare"
          token: ${{ secrets.TOKEN }}
          tag: "casebin"
          fileName: ${{ secrets.TBSTAFF_00080101 }}.md
          out-file-path: ./resolve
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  clean:
    if: always()
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        if: always()
        with:
          name: github-pages
