name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

  repository_dispatch:
    types: [Dispatched]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout AFS
        uses: actions/checkout@v4
        with:
          repository: Kee7702/AltFileShare
          token: ${{ secrets.TOKEN }}
          path: ./${{ secrets.AFS_ID }}
      - name: Checkout TSS
        uses: actions/checkout@v4
        with:
          repository: Kee7702/ToolboxStaffShare
          token: ${{ secrets.TOKEN }}
          path: ./${{ secrets.TSS_ID }}
      - name: Download AFSLFS
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "Kee7702/AltFileShare"
          token: ${{ secrets.TOKEN }}
          tag: "lfs"
          out-file-path: ./${{ secrets.AFS_ID }}/lfs
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5

  clean:
    if: always()
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v5.1.0
        if: always()
        with:
          name: github-pages
